### ISSUE TITLE
With Karabiner running the Function key is recognized but without it is.

### ISSUE THREAD

**Issue by mhinton** [tekezo/Files#8]
These are my current settings. The F1-F6 / F10-F12 keys work. However the F7,F8,F9 keys don't do anything. I would like the Fn+F1-F12 key combos to send the function key value. If I quite Karabiner then the F1-F12 keys send the function key value. I am using the latest version of Karabiner.

![karabiner](https://cloud.githubusercontent.com/assets/23145/9477266/07c651cc-4b37-11e5-9454-a142502408b5.png)

**Comment by tekezo** [comment]
The f7-f9 works well on my machine.
Do these keys not work even if you opened iTunes?

> I would like the Fn+F1-F12 key combos

What's your keyboard device.
Generally, Karabiner does not support the fn key in third party keyboard. (eg. Logitech)

If you are using such third party keyboard, you should use other modifier to send normal f1-f12 key events, for example, send f1 event by command-f1.

Use new setting by this private.xml together:
https://github.com/tekezo/Files/blob/master/Karabiner/private.command_fx_to_fx/private.xml

How to use private.xml:
https://pqrs.org/osx/karabiner/document.html#privatexml

**Comment by mhinton** [comment]
I am using a rev 2 Code Keyboard. The private.xml settings you posted work for all but command-F11 which causes the windows to be hidden and the desktop to be shown. 

I discovered the F7/F8/F9 keys not working was Google Chrome's fault. 

http://www.omgchrome.com/chrome-google-music-media-keys/

Thanks for your quick response and help.

**Comment by tekezo** [comment]
If you want to use F11 in apps, you have to disable the system wide shortcut.
Open System Preferences > Keyboard > Shortcuts > Mission Control, then disable "Show Desktop".

<img width="657" alt="screen shot 2015-08-26 at 11 49 04 pm" src="https://cloud.githubusercontent.com/assets/659178/9496793/10e0e800-4c4d-11e5-8b5f-af42378f428a.png">
